#!/bin/bash
# Embed userspace binary in kernel filesystem

set -e

USERSPACE_DIR="/var/www/rustux.com/prod/kernel/userspace"
KERNEL_EFI_DIR="/var/www/rustux.com/prod/kernel/kernel-efi"

# Build userspace binary
echo "Building userspace binary..."
cd "$USERSPACE_DIR"
cargo build --release --target x86_64-unknown-none

# Get binary path
BINARY="$USERSPACE_DIR/target/x86_64-unknown-none/release/rustux-userspace"

# Check if binary exists
if [ ! -f "$BINARY" ]; then
    echo "Error: Binary not found at $BINARY"
    exit 1
fi

# Get binary size
SIZE=$(stat -c%s "$BINARY" 2>/dev/null || stat -f%z "$BINARY" 2>/dev/null)
echo "Binary size: $SIZE bytes"

# Create Rust file with embedded binary using proper hex format
cat > "$KERNEL_EFI_DIR/src/userspace_bin.rs" <<EOF
// Copyright 2025 The Rustux Authors
//
// Auto-generated from userspace binary
// DO NOT EDIT - Generated by embed_userspace.sh

/// Embedded userspace test program binary
pub const USERSPACE_BIN: &[u8] = include_bytes!("../../userspace/target/x86_64-unknown-none/release/rustux-userspace");
EOF

echo "Embedded userspace binary in kernel-efi/src/userspace_bin.rs"
echo "Using include_bytes! macro for $SIZE bytes"
