// Copyright 2025 The Rustux Authors
//
// Auto-generated from userspace binary
// DO NOT EDIT - Generated by embed_userspace.sh

#![allow(dead_code)]

/// Embedded userspace test program binary
// TODO: Re-enable after fixing userspace build
// pub const USERSPACE_BIN: &[u8] = include_bytes!("../../userspace/test/target/x86_64-unknown-none/release/rustux-userspace-test");
pub const USERSPACE_BIN: &[u8] = &[];
