// Copyright 2025 The Rustux Authors
//
// Auto-generated from userspace binary
// DO NOT EDIT - Generated by embed_userspace.sh

/// Embedded userspace test program binary
pub const USERSPACE_BIN: &[u8] = include_bytes!("../../userspace/target/x86_64-unknown-none/release/rustux-userspace");
